telegram:
  token: #Токен ТГ
  picnicChatID: #Куда будет приходить ответ бота
  maxMessageSize: #Максимальный размер сообщения
  maxQueueSize: #Максимальное кол-во сообщений в буфере сообщений
  debugChatID: #Куда будет приходить дебаг сообщения бота

openai:
  countRepeatedRequests: #Кол-во попыток отправки запросов
  token: #Токен ML
  gptURL: #URL ML
  whatPrompt: #Промпт для ML, команда /what
  sayPrompt: #Промпт для ML, команда /say
